version: '3.8'

services:
  markitdown-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: markitdown-mcp-server
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - LOG_LEVEL=DEBUG
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
